### ISSUE TITLE
pdf2md doesn't work

### ISSUE THREAD

**Issue by Jecs9** [johnlinp/pdf-to-markdown#18]
Dear pdf2md team,

I am using python36, whenever I try to convert a pdf to markdown with your library there is no effect at all, nothing is given as output or anything

I have tried to go file by file and build it and I have found that python36 shows some errors in some files, for example the encoding: utf8 is shown as error so I have replaced it for encoding: utf-8 in the files I have seen that need encoding but still nothing happens

Could you please be more precise on how is this suppose to work?

Thank you in advance

Have a good day

**Comment by johnlinp** [comment]
pdf2md doesn't support Python 3.x, yet. Please wait for #19 to be fixed.
