### ISSUE TITLE
No module named pdfdocument

### ISSUE THREAD

**Issue by yinflying** [johnlinp/pdf-to-markdown#9]
Thanks a lot !
But there is a problem if we use `sudo apt-get install python-pdfminer`, the error code is:
`ImportError: No module named pdfdocument`
but after update the pdfminer, the problem solved:
`sudo pip install --upgrade pdfminer`

maybe because of my old source---- ubuntu 14.04?

**Comment by johnlinp** [comment]
Thanks for the update!
